//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.20 at 04:02:32 PM NOVT 
//


package kuzminov;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelationsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelationsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="parent" type="{http://fit.nsu.ru/people}RefType" minOccurs="0"/&gt;
 *         &lt;element name="father" type="{http://fit.nsu.ru/people}RefType" minOccurs="0"/&gt;
 *         &lt;element name="mother" type="{http://fit.nsu.ru/people}RefType" minOccurs="0"/&gt;
 *         &lt;element name="spouse" type="{http://fit.nsu.ru/people}RefType" minOccurs="0"/&gt;
 *         &lt;element name="husband" type="{http://fit.nsu.ru/people}RefType" minOccurs="0"/&gt;
 *         &lt;element name="wife" type="{http://fit.nsu.ru/people}RefType" minOccurs="0"/&gt;
 *         &lt;element name="child" type="{http://fit.nsu.ru/people}RefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="son" type="{http://fit.nsu.ru/people}RefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="daughter" type="{http://fit.nsu.ru/people}RefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="sibling" type="{http://fit.nsu.ru/people}RefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="brother" type="{http://fit.nsu.ru/people}RefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="sister" type="{http://fit.nsu.ru/people}RefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationsType", propOrder = {
    "parent",
    "father",
    "mother",
    "spouse",
    "husband",
    "wife",
    "child",
    "son",
    "daughter",
    "sibling",
    "brother",
    "sister"
})
public class RelationsType {

    protected RefType parent;
    protected RefType father;
    protected RefType mother;
    protected RefType spouse;
    protected RefType husband;
    protected RefType wife;
    protected List<RefType> child;
    protected List<RefType> son;
    protected List<RefType> daughter;
    protected List<RefType> sibling;
    protected List<RefType> brother;
    protected List<RefType> sister;

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setParent(RefType value) {
        this.parent = value;
    }

    /**
     * Gets the value of the father property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getFather() {
        return father;
    }

    /**
     * Sets the value of the father property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setFather(RefType value) {
        this.father = value;
    }

    /**
     * Gets the value of the mother property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getMother() {
        return mother;
    }

    /**
     * Sets the value of the mother property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setMother(RefType value) {
        this.mother = value;
    }

    /**
     * Gets the value of the spouse property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getSpouse() {
        return spouse;
    }

    /**
     * Sets the value of the spouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setSpouse(RefType value) {
        this.spouse = value;
    }

    /**
     * Gets the value of the husband property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getHusband() {
        return husband;
    }

    /**
     * Sets the value of the husband property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setHusband(RefType value) {
        this.husband = value;
    }

    /**
     * Gets the value of the wife property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getWife() {
        return wife;
    }

    /**
     * Sets the value of the wife property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setWife(RefType value) {
        this.wife = value;
    }

    /**
     * Gets the value of the child property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the child property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChild().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefType }
     * 
     * 
     */
    public List<RefType> getChild() {
        if (child == null) {
            child = new ArrayList<RefType>();
        }
        return this.child;
    }

    /**
     * Gets the value of the son property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the son property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefType }
     * 
     * 
     */
    public List<RefType> getSon() {
        if (son == null) {
            son = new ArrayList<RefType>();
        }
        return this.son;
    }

    /**
     * Gets the value of the daughter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the daughter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDaughter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefType }
     * 
     * 
     */
    public List<RefType> getDaughter() {
        if (daughter == null) {
            daughter = new ArrayList<RefType>();
        }
        return this.daughter;
    }

    /**
     * Gets the value of the sibling property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sibling property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSibling().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefType }
     * 
     * 
     */
    public List<RefType> getSibling() {
        if (sibling == null) {
            sibling = new ArrayList<RefType>();
        }
        return this.sibling;
    }

    /**
     * Gets the value of the brother property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the brother property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrother().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefType }
     * 
     * 
     */
    public List<RefType> getBrother() {
        if (brother == null) {
            brother = new ArrayList<RefType>();
        }
        return this.brother;
    }

    /**
     * Gets the value of the sister property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sister property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSister().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefType }
     * 
     * 
     */
    public List<RefType> getSister() {
        if (sister == null) {
            sister = new ArrayList<RefType>();
        }
        return this.sister;
    }

}
